const productos = [
    {
        id: 1,
        titulo: "Andes-origen-roja",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Andes origen-roja.png",
    },
    {
        id: 2,
        titulo: "Andes-origen-verde",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Andes origen-verde.png",
    },
    {
        id: 3,
        titulo: "Corona-lata",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Corona-lata.png",
    },
    {
        id: 4,
        titulo: "Corona",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Corona.png",
    },
    {
        id: 5,
        titulo: "Estrella-galicia",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Estrella-galicia.png",
    },
    {
        id: 6,
        titulo: "Heineken-lata",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Heineken-latapng.png",
    },
    {
        id: 7,
        titulo: "Heineken-vidrio",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Heineken-vidrio.png",
    },
    {
        id: 8,
        titulo: "Imperial-cream",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Imperial-Cream.png",
    },
    {
        id: 9,
        titulo: "Imperial-lager",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Imperial-lager.png",
    },
    {
        id: 10,
        titulo: "Quilmes-clasica",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Quilmes-clasica.png",
    },
    {
        id: 11,
        titulo: "QuilmesredLager",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Quilmes-redlager.png",
    },
    {
        id: 12,
        titulo: "Quilmes-sinAlcohol",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Quilmes-sinAlcohol.png",
    },
    {
        id: 13,
        titulo: "Quilmes-stout",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Quilmes-stout.png",
    },
    {
        id: 14,
        titulo: "Schneider-lata-700",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Schneider-lata-700.png",
    },
    {
        id: 15,
        titulo: "Schneider-lata",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Schneider-lata.png",
    },
    {
        id: 1,
        titulo: "Stella-artois",
        precio: 32000,
        cantidad: 1,
        img: "/cliente/media/img/Stella-artois.png",
    },

]


